server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/planner_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public

jwt:
  password:
    encoder:
      secret: F2K2DZ82odq$13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      key-length: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f86df20a499a7d3f91ff2a7c
  expiration: 7200
  issuer: PLANNER

minio:
  endpoint: http://minio:9000
  access-key: laUeEl4q29fhaqQhd76d
  secret-key: 9nlPYGoplkbbd61uCU88GDXBWQf3TY18dkeZEx3m
  bucket-name: it-planner
  region: us-east-1
  secure: false

springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.laba.it_planner.controller

logging:
  level:
    org.springdoc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true