server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://postgres-user:5433/planner_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
  mail:
    host: connect.smtp.bz
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      thread_count: ${SPRING_MAIL_TREAD_COUNT}
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  password:
    encoder:
      secret: ${JWT_PASSWORD_SECRET}
      iteration: 64
      key-length: 256
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  issuer: PLANNER

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}
  region: us-east-1
  secure: false

springdoc:
  swagger-ui:
    enabled: true
    path: /api/v1/swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.laba.it_planner.controller

logging:
  level:
    org.springdoc: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true